repos:
-   repo: local
    hooks:
      - id: envo-isort
        name: "Envo: sort imports."
        entry: .bin/os.isort
        language: script
        files: '.*.py$'
        exclude: ".*/templates"

      - id: envo-black
        name: "Envo: Make it black."
        entry: .bin/os.black
        language: script
        files: '.*.py$'
        exclude: ".*/templates"

      - id: envo-autoflake
        name: "Envo: Autoflake."
        entry: .bin/os.autoflake
        language: script
        files: '.*.py$'
        exclude: ".*/templates"
