version: 2.19

workflows:
  version: 2
  test:
    jobs:
      - test-3-6
      - test-3-7
      - test-3-8
      - flake8
      - mypy
      - publish:
          requires:
            - flake8
            - mypy
            - test-3-6
            - test-3-7
            - test-3-8
          filters:
            branches:
              only: master
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/

defaults: &defaults
  docker:
    - image: circleci/python:3.8.2

cache-key: &cache-key
  deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}

restore_cache: &restore_cache
  restore_cache:
    name: "Restore cache"
    key: *cache-key

save_cache: &save_cache
  save_cache:
    key: *cache-key
    paths:
     - .venv


bootstrap: &bootstrap
  run:
    name: Bootstrap
    command: ./bootstrap


orbs:
  codecov: codecov/codecov@1.0.2


jobs:
  flake8:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *bootstrap
      - run:
          name: Flake8
          command: poetry run flake8
      - *save_cache

  mypy:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *bootstrap
      - run:
          name: Mypy
          command: poetry run mypy .
      - *save_cache

  test-3-8: &test-template
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *bootstrap
      - run:
          name: Test
          command: poetry run pytest tests
      - *save_cache

  test-3-7:
    <<: *test-template
    image: circleci/python:3.7

  test-3-6:
    <<: *test-template
    image: circleci/python:3.6

  upload-codecov:
    working_directory: /srv
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: Init
          command: sudo chown circleci:circleci /srv
      - checkout
      - run:
          name: Create workspace
          command: mkdir -p workspace
      - attach_workspace:
          at: workspace
      - run:
          name: Upload
          command: |
            curl -s https://codecov.io/bash | bash -s -- \
            -t "${CODECOV_TOKEN}" \
            -n "${CIRCLE_BUILD_NUM}" \
            -y ".codecov.yml" \
            -f "./workspace/test-results/coverage.xml" \
            -Z || echo 'Codecov upload failed'
      - run:
          - codecov/upload


  publish:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *bootstrap
      - run:
          name: Recreate stubs
          command: poetry run ./.bin/recreate_stubs
      - run:
          name: Generate version
          command: poetry run ./.bin/generate_version
      - run:
          name: Build
          command: poetry build
      - run:
          name: publish
          command: poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD
